### ISSUE TITLE
Failed provisions loop forever

### ISSUE THREAD

**Issue by grahamc** [input-output-hk/nixops-packet#10]
```
s1-large-storage-test> instance is in failed state
s1-large-storage-test> instance is in failed state
s1-large-storage-test> instance is in failed state
s1-large-storage-test> instance is in failed state
s1-large-storage-test> instance is in failed state
```

**Comment by johnalotoski** [comment]
I might have some difficulty reproducing that (I've never had it occur).  Any suggestions on handling?  It's easy enough to add an exception on failed state detection.  I'll check if any other cleanup would need to be done also prior to exit.

**Comment by johnalotoski** [comment]
Fixed in https://github.com/input-output-hk/nixops-packet/commit/d5ef2c4e2dd789e5a4f23df84792ec94039bf195 by adding a failed state case.

**Comment by johnalotoski** [comment]
Closing.  Re-open this ticket or create a new ticket if the issue persists.
