### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by nuxeh** [input-output-hk/nixops-packet#17]
This really needs some documentation, I have no idea how to start installing, or using it!

**Comment by johnalotoski** [comment]
We're trying to address some basic functional issues with packet and also for compatibility with nixops 2.0 first.
Then some documentation will be added.  Another comment will be added here once that is done.

**Comment by johnalotoski** [comment]
A basic `README.md` file has been added to the repo.  The docs will be expanded over time with more helpful info.
