### ISSUE TITLE
setting deployment.customdata doesn't work, but also doesn't error

### ISSUE THREAD

**Issue by grahamc** [input-output-hk/nixops-packet#6]
Setting It should be `customData`, but the module system doesn't seem to validate this. Not sure if there is a better way, but I got bit by this.

**Comment by johnalotoski** [comment]
Setting customData under `deployment.packet.customData` works as of now, which I think is what you are referring to.
There was a recent nixops2 fixup for that here: https://github.com/input-output-hk/nixops-packet/commit/18c81587fb04ac2d08b957dd76603e2214823f76.

**Comment by johnalotoski** [comment]
Please re-open if I misunderstood the problem and it still exists.
